/**
 * L'Atelier Gourmet - Complete Restaurant Menu Catalog
 * Based on the reference Restaurant Menu design with 7 tactile volumes and 35+ items.
 */

export const RESTAURANT_INFO = {
  name: "L'Atelier Gourmet",
  subname: "Food & Drink Menu & Opening Hour Sign",
  cityTitle: "THE BEST CAFE IN YOUR CITY",
  est: "EST 2023",
  openHours: "3PM - 10PM",
  openHoursSubtitle: "Daily Dining & Weekend Brunch",
  address: "1234 Utown City, Cambridge, Metropolis 201200",
  website: "www.yourwebsite.com",
  social: "@yourrestaurant",
  phone: "+1 (555) 234-5678",
  currency: "$",
  taxRate: 0.08
};

export const MENU_VOLUMES = [
  {
    id: "starters",
    title: "Food Starter",
    shortTitle: "Starters",
    roman: "I",
    discipline: "Appetizers & Bites",
    note: "Crispy bites, artisan breads, and savory openers.",
    deck: "A curated prelude to your dining experience. Crafted with hand-cut potatoes, local cheeses, ocean-fresh fish, and fragrant roasted garlic baguettes.",
    binding: "Emerald Cloth · Gold Leaf Foil",
    format: "148 × 216 mm · Volume I",
    theme: "Starters · Freshly Crisped & Seasoned",
    motif: "Artisan Wheat & Fork",
    motifKey: "wheat",
    paletteLabel: "Deep Emerald · Cream · Antique Gold",
    color: "#1b382b",
    foil: "#e5c07b",
    palette: {
      paper: "#122019",
      paperDeep: "#0a1410",
      paperPale: "#f5f0e6",
      ink: "#f4eee6",
      inkSoft: "#a8b8ae",
      wall: "#122019",
      shelf: "#3a2118",
      shelfDark: "#1c0e0a",
      light: "#f9e8cb",
      fill: "#6f9c84"
    },
    width: 1.04,
    height: 1.58,
    depth: 0.28,
    seed: 101,
    items: [
      {
        id: "fish-chip-cheese",
        name: "Fish Chip Cheese",
        price: 10,
        category: "Food Starter",
        description: "Golden crispy beer-battered whitefish fillets served over thick-cut chips and crowned with molten aged cheddar and house tartare sauce.",
        image: "https://images.unsplash.com/photo-1579208030886-b937da0925dc?auto=format&fit=crop&w=800&q=80",
        calories: "480 kcal",
        allergens: ["Fish", "Dairy", "Gluten"],
        tags: ["Popular", "Chef's Choice"],
        prepTime: "12 mins"
      },
      {
        id: "potatoes-wedge",
        name: "Potatoes Wedge",
        price: 10,
        category: "Food Starter",
        description: "Rustic skin-on potato wedges seasoned with smoked paprika, sea salt, rosemary, and served with a zesty roasted garlic aioli.",
        image: "https://images.unsplash.com/photo-1573080496219-bb080dd4f877?auto=format&fit=crop&w=800&q=80",
        calories: "360 kcal",
        allergens: ["Eggs"],
        tags: ["Vegetarian", "Gluten-Free"],
        prepTime: "10 mins"
      },
      {
        id: "cheese-chips",
        name: "Cheese Chips",
        price: 10,
        category: "Food Starter",
        description: "Hand-cut triple-cooked Idaho potato fries smothered in warm artisan Monterey Jack, sharp cheddar sauce, and scallions.",
        image: "https://images.unsplash.com/photo-1586190848861-99aa4a171e90?auto=format&fit=crop&w=800&q=80",
        calories: "420 kcal",
        allergens: ["Dairy"],
        tags: ["Vegetarian", "Popular"],
        prepTime: "8 mins"
      },
      {
        id: "garlic-bread",
        name: "Garlic Bread",
        price: 10,
        category: "Food Starter",
        description: "French baguette slices toasted with rich compound butter of confit garlic, Italian parsley, fleur de sel, and shaved Parmigiano-Reggiano.",
        image: "https://images.unsplash.com/photo-1619535860434-ba1d8fa12536?auto=format&fit=crop&w=800&q=80",
        calories: "310 kcal",
        allergens: ["Gluten", "Dairy"],
        tags: ["Vegetarian"],
        prepTime: "7 mins"
      },
      {
        id: "chicken-parmesan-starter",
        name: "Chicken Parmesan Starter",
        price: 10,
        category: "Food Starter",
        description: "Crisp golden panko-crusted chicken tenderloins baked in San Marzano tomato marinara and bubbly fresh mozzarella.",
        image: "https://images.unsplash.com/photo-1632778149955-e80f8ceca2e8?auto=format&fit=crop&w=800&q=80",
        calories: "510 kcal",
        allergens: ["Gluten", "Dairy", "Eggs"],
        tags: ["House Favorite"],
        prepTime: "14 mins"
      }
    ]
  },
  {
    id: "main-course",
    title: "Main Course",
    shortTitle: "Mains",
    roman: "II",
    discipline: "Hearty Classics & Stone-Baked Pizzas",
    note: "Signature Italian classics and artisanal pizzas.",
    deck: "Centerpiece dishes prepared with slow-simmered sauces, prime poultry, and authentic dough fermented for 48 hours and fired to blistered perfection.",
    binding: "Ruby Cloth · Rose Gold Foil",
    format: "156 × 228 mm · Volume II",
    theme: "Main Course · Richly Layered & Oven-Fired",
    motif: "Stone Oven & Flames",
    motifKey: "oven",
    paletteLabel: "Imperial Ruby · Blush · Rose Gold",
    color: "#8a2424",
    foil: "#f4a896",
    palette: {
      paper: "#241010",
      paperDeep: "#150808",
      paperPale: "#fbeae6",
      ink: "#fff0eb",
      inkSoft: "#d6aba0",
      wall: "#241010",
      shelf: "#421e14",
      shelfDark: "#1c0d08",
      light: "#ffd6cc",
      fill: "#c45c5c"
    },
    width: 1.1,
    height: 1.62,
    depth: 0.3,
    seed: 202,
    items: [
      {
        id: "main-cabonara",
        name: "Cabonara",
        price: 10,
        category: "Main Course",
        description: "Classic Roman spaghetti tossed with crisped guanciale, pasture-raised egg yolk emulsion, aged Pecorino Romano, and freshly cracked Tellicherry pepper.",
        image: "https://images.unsplash.com/photo-1612874742237-6526221588e3?auto=format&fit=crop&w=800&q=80",
        calories: "640 kcal",
        allergens: ["Gluten", "Eggs", "Dairy", "Pork"],
        tags: ["Signature", "Chef's Choice"],
        prepTime: "15 mins"
      },
      {
        id: "main-chicken-parmesan",
        name: "Chicken Parmesan",
        price: 10,
        category: "Main Course",
        description: "Generous herb-crusted chicken breast cutlet bathed in slow-cooked tomato sugo, topped with melted Buffalo mozzarella, over buttered fettuccine.",
        image: "https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=800&q=80",
        calories: "720 kcal",
        allergens: ["Gluten", "Dairy", "Eggs"],
        tags: ["House Favorite", "Popular"],
        prepTime: "18 mins"
      },
      {
        id: "bbq-chicken-pizza",
        name: "BBQ Chicken Pizza",
        price: 10,
        category: "Main Course",
        description: "Hand-stretched sourdough pizza with smoked hickory barbecue sauce, tender pulled chicken breast, caramelized red onions, smoked provolone, and fresh cilantro.",
        image: "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?auto=format&fit=crop&w=800&q=80",
        calories: "790 kcal",
        allergens: ["Gluten", "Dairy"],
        tags: ["Popular"],
        prepTime: "16 mins"
      },
      {
        id: "veggie-pizza",
        name: "Veggie Pizza",
        price: 10,
        category: "Main Course",
        description: "Crisp Neapolitan crust layered with fire-roasted bell peppers, cremini mushrooms, grilled zucchini, kalamata olives, sweet cherry tomatoes, and vegan mozzarella.",
        image: "https://images.unsplash.com/photo-1574071318508-1cdbab80d002?auto=format&fit=crop&w=800&q=80",
        calories: "580 kcal",
        allergens: ["Gluten"],
        tags: ["Vegetarian", "Vegan Option"],
        prepTime: "15 mins"
      }
    ]
  },
  {
    id: "pasta",
    title: "Pasta Traditions",
    shortTitle: "Pasta",
    roman: "III",
    discipline: "Artisanal Semolina & Rich Sauces",
    note: "Bronze-die extruded pasta simmered in heritage sauces.",
    deck: "Honoring Italian culinary roots with fresh bronze-cut pasta tossed in velvety cheeses, slow-simmered prime ragù, and fragrant sweet Genovese basil.",
    binding: "Tuscan Ochre Cloth · Copper Foil",
    format: "144 × 214 mm · Volume III",
    theme: "Pasta · Simmered to Perfection",
    motif: "Twirled Fork & Olive Branch",
    motifKey: "pasta",
    paletteLabel: "Tuscan Ochre · Ivory · Burnt Copper",
    color: "#a4631e",
    foil: "#f3c27e",
    palette: {
      paper: "#26170a",
      paperDeep: "#170e05",
      paperPale: "#fff2e0",
      ink: "#fff2df",
      inkSoft: "#dbb48c",
      wall: "#26170a",
      shelf: "#3a2118",
      shelfDark: "#1c0e0a",
      light: "#ffe0b2",
      fill: "#c88544"
    },
    width: 0.98,
    height: 1.54,
    depth: 0.26,
    seed: 303,
    items: [
      {
        id: "meat-balls-pasta",
        name: "Meat Balls Pasta",
        price: 10,
        category: "Pasta",
        description: "Tender handmade prime beef and pork meatballs simmered for four hours in sweet San Marzano tomato pomodoro over al dente spaghetti with fresh basil.",
        image: "https://images.unsplash.com/photo-1551183053-bf91a1d81141?auto=format&fit=crop&w=800&q=80",
        calories: "690 kcal",
        allergens: ["Gluten", "Dairy", "Eggs"],
        tags: ["Classic Favorite", "Chef's Pick"],
        prepTime: "14 mins"
      },
      {
        id: "pasta-cabonara",
        name: "Cabonara",
        price: 10,
        category: "Pasta",
        description: "Silky ribbon fettuccine coated in farm egg emulsion, double-smoked pancetta lardons, cracked black peppercorn, and aged 24-month Parmigiano-Reggiano.",
        image: "https://images.unsplash.com/photo-1621996346565-e3d5d62810f4?auto=format&fit=crop&w=800&q=80",
        calories: "630 kcal",
        allergens: ["Gluten", "Eggs", "Dairy", "Pork"],
        tags: ["Signature"],
        prepTime: "12 mins"
      },
      {
        id: "super-cheesy-pasta",
        name: "Super Cheesy Pasta",
        price: 10,
        category: "Pasta",
        description: "Rigatoni pasta baked in a decadent four-cheese fondue of Taleggio, Gorgonzola Dolce, Fontina, and sharp white cheddar with a herb crumb topping.",
        image: "https://images.unsplash.com/photo-1608897013039-887f21d8c804?auto=format&fit=crop&w=800&q=80",
        calories: "740 kcal",
        allergens: ["Gluten", "Dairy"],
        tags: ["Vegetarian", "Cheesy"],
        prepTime: "15 mins"
      }
    ]
  },
  {
    id: "specials-breakfast",
    title: "Special & Breakfast",
    shortTitle: "Specials",
    roman: "IV",
    discipline: "All-Day Comfort & Chef's Creations",
    note: "All-day breakfast skillet and specialty comfort plates.",
    deck: "Morning comfort meets evening indulgence. Featuring our celebrated All Day Breakfast with fresh coffee, creamy baked mac, and gourmet salads.",
    binding: "Ultramarine Cloth · Polished Brass Foil",
    format: "160 × 236 mm · Volume IV",
    theme: "Special Menu · Sunrise to Sunset Dining",
    motif: "Sunburst & Coffee Mug",
    motifKey: "sunburst",
    paletteLabel: "Ultramarine · Honey · Polished Brass",
    color: "#1a355b",
    foil: "#e8c566",
    palette: {
      paper: "#0e1c31",
      paperDeep: "#08101e",
      paperPale: "#eef4fd",
      ink: "#f0f5fc",
      inkSoft: "#a4bede",
      wall: "#0e1c31",
      shelf: "#3a2118",
      shelfDark: "#1c0e0a",
      light: "#fae7af",
      fill: "#4f7cb5"
    },
    width: 1.08,
    height: 1.64,
    depth: 0.32,
    seed: 404,
    items: [
      {
        id: "all-day-breakfast",
        name: "All Day Breakfast with Coffee",
        price: 10,
        category: "Special Menu",
        description: "Sunny farm eggs, grilled Cumberland sausage, smoked streaky bacon, buttered button mushrooms, baked beans, roasted vine tomatoes, sourdough toast & artisan brewed coffee.",
        image: "https://images.unsplash.com/photo-1533089860892-a7c6f0a88666?auto=format&fit=crop&w=800&q=80",
        calories: "780 kcal",
        allergens: ["Eggs", "Gluten", "Pork"],
        tags: ["Special Set", "Includes Coffee", "Chef's Choice"],
        prepTime: "12 mins"
      },
      {
        id: "mac-n-cheese",
        name: "Mac n Cheese",
        price: 10,
        category: "Special Menu",
        description: "Elbow macaroni enveloped in a velvety three-cheese mornay sauce, baked with a golden crunchy panko parmesan crust and fresh thyme.",
        image: "https://images.unsplash.com/photo-1543339308-43e59d6b73a6?auto=format&fit=crop&w=800&q=80",
        calories: "680 kcal",
        allergens: ["Gluten", "Dairy"],
        tags: ["Comfort Classic", "Vegetarian"],
        prepTime: "14 mins"
      },
      {
        id: "chicken-with-salad",
        name: "Chicken with Salad",
        price: 10,
        category: "Special Menu",
        description: "Char-grilled lemon rosemary chicken breast served alongside crisp romaine, baby spinach, avocado, cherry tomatoes, and aged balsamic glaze.",
        image: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=800&q=80",
        calories: "450 kcal",
        allergens: [],
        tags: ["Healthy Pick", "Gluten-Free", "Low Carb"],
        prepTime: "12 mins"
      },
      {
        id: "red-velvet-cheese-cake",
        name: "Red Velvet Cheese Cake",
        price: 10,
        category: "Special Menu",
        description: "Double layered cocoa-rich red velvet cake swirled with New York style vanilla bean cheesecake on a buttery graham cracker crust.",
        image: "https://images.unsplash.com/photo-1586985289688-ca3cf47d3e6e?auto=format&fit=crop&w=800&q=80",
        calories: "520 kcal",
        allergens: ["Dairy", "Eggs", "Gluten"],
        tags: ["Sweet Specialty", "Popular"],
        prepTime: "5 mins"
      }
    ]
  },
  {
    id: "burger",
    title: "Gourmet Burgers",
    shortTitle: "Burgers",
    roman: "V",
    discipline: "Seared Patties & Brioche Buns",
    note: "Prime Angus cuts, charcoal buns, and signature sauces.",
    deck: "Burgers crafted with zero compromise: 100% prime Angus beef smashed and seared hot, nestled inside toasted artisan brioche with house-pickled toppings.",
    binding: "Espresso Leather Cloth · Pure Silver Foil",
    format: "152 × 222 mm · Volume V",
    theme: "Burgers · Sizzled & Layered",
    motif: "Brioche Bun & Grill",
    motifKey: "grill",
    paletteLabel: "Deep Charcoal · Silver · Warm Toffee",
    color: "#282321",
    foil: "#d3d8de",
    palette: {
      paper: "#1a1615",
      paperDeep: "#0f0d0c",
      paperPale: "#f0ece9",
      ink: "#f4f1ee",
      inkSoft: "#a89f9b",
      wall: "#1a1615",
      shelf: "#3a2118",
      shelfDark: "#1c0e0a",
      light: "#ebeff3",
      fill: "#7a6e69"
    },
    width: 1.02,
    height: 1.56,
    depth: 0.29,
    seed: 505,
    items: [
      {
        id: "the-classic-burger",
        name: "The Classic Burger",
        price: 10,
        category: "Burger",
        description: "6oz prime Angus beef patty, melted Wisconsin cheddar, butterhead lettuce, heirloom tomato, dill pickle spear, and secret diner sauce on a toasted brioche bun.",
        image: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=800&q=80",
        calories: "710 kcal",
        allergens: ["Gluten", "Dairy", "Eggs"],
        tags: ["Bestseller", "Signature"],
        prepTime: "12 mins"
      },
      {
        id: "charcoal-burger",
        name: "Charcoal Burger",
        price: 10,
        category: "Burger",
        description: "House-baked Japanese activated charcoal bun with twin smashed Angus patties, smoked bacon jam, caramelized Spanish onions, and black truffle aioli.",
        image: "https://images.unsplash.com/photo-1586190848861-99aa4a171e90?auto=format&fit=crop&w=800&q=80",
        calories: "820 kcal",
        allergens: ["Gluten", "Dairy", "Eggs", "Pork"],
        tags: ["Gourmet Special", "Chef's Choice"],
        prepTime: "15 mins"
      },
      {
        id: "chicken-burger",
        name: "Chicken Burger",
        price: 10,
        category: "Burger",
        description: "Buttermilk marinated fried chicken thigh, crisp red cabbage slaw, bread-and-butter pickles, and spicy hot-honey glaze on a sesame brioche bun.",
        image: "https://images.unsplash.com/photo-1625813506062-0aeb1d7a094b?auto=format&fit=crop&w=800&q=80",
        calories: "670 kcal",
        allergens: ["Gluten", "Dairy", "Eggs"],
        tags: ["Crispy", "Popular"],
        prepTime: "14 mins"
      }
    ]
  },
  {
    id: "fresh-drinks",
    title: "Fresh Drinks",
    shortTitle: "Drinks",
    roman: "VI",
    discipline: "Botanical Juices, Craft Beers & Teas",
    note: "Cold-pressed juices, refreshing sodas, and loose-leaf brews.",
    deck: "Quench your thirst with freshly squeezed citrus, handcrafted botanical sodas, small-batch local beers on draft, and steeped loose-leaf teas.",
    binding: "Cerulean Blue Cloth · Platinum Foil",
    format: "146 × 224 mm · Volume VI",
    theme: "Drinks · Chilled & Botanically Infused",
    motif: "Citrus Wheel & Botanical Sprig",
    motifKey: "cocktail",
    paletteLabel: "Cerulean · Aqua · Sparkling Frost",
    color: "#184e68",
    foil: "#bce5f5",
    palette: {
      paper: "#0c2330",
      paperDeep: "#061219",
      paperPale: "#e6f6fd",
      ink: "#eef9ff",
      inkSoft: "#9ac3d8",
      wall: "#0c2330",
      shelf: "#3a2118",
      shelfDark: "#1c0e0a",
      light: "#def2fc",
      fill: "#458fae"
    },
    width: 0.96,
    height: 1.58,
    depth: 0.24,
    seed: 606,
    items: [
      {
        id: "fresh-juice",
        name: "Fresh Juice",
        price: 5,
        category: "Fresh Drinks",
        description: "Choice of freshly cold-pressed Valencia orange, ruby red grapefruit, or green apple cucumber detox juice served over ice.",
        image: "https://images.unsplash.com/photo-1613478223719-2ab802602423?auto=format&fit=crop&w=800&q=80",
        calories: "120 kcal",
        allergens: [],
        tags: ["Cold Pressed", "Vegan"],
        prepTime: "3 mins"
      },
      {
        id: "house-beers",
        name: "House Beers",
        price: 5,
        category: "Fresh Drinks",
        description: "Rotating selection of cold draft craft beers: Crisp German Pilsner, Pacific Hazy IPA, or Caramel Amber Ale (16oz pint).",
        image: "https://images.unsplash.com/photo-1608270586620-248524c67de9?auto=format&fit=crop&w=800&q=80",
        calories: "180 kcal",
        allergens: ["Gluten"],
        tags: ["Draft Beer", "Alcohol 21+"],
        prepTime: "2 mins"
      },
      {
        id: "all-soda",
        name: "All Soda",
        price: 5,
        category: "Fresh Drinks",
        description: "Artisanal glass-bottled craft cane sugar colas, blood orange spritzers, Mexican Coke, and vintage root beers.",
        image: "https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?auto=format&fit=crop&w=800&q=80",
        calories: "140 kcal",
        allergens: [],
        tags: ["Sparkling", "Refreshing"],
        prepTime: "2 mins"
      },
      {
        id: "soda-water",
        name: "Soda Water",
        price: 5,
        category: "Fresh Drinks",
        description: "Sparkling natural San Pellegrino mineral water with fresh cucumber ribbons, crushed mint, and lemon twist.",
        image: "https://images.unsplash.com/photo-1551024709-8f23befc6f87?auto=format&fit=crop&w=800&q=80",
        calories: "0 kcal",
        allergens: [],
        tags: ["Zero Calorie", "Refreshing"],
        prepTime: "2 mins"
      },
      {
        id: "ginger-ale",
        name: "Ginger Ale",
        price: 5,
        category: "Fresh Drinks",
        description: "Organic fermented ginger brew infused with kaffir lime zest, lemongrass, and sparkling spring water.",
        image: "https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?auto=format&fit=crop&w=800&q=80",
        calories: "95 kcal",
        allergens: [],
        tags: ["Organic", "Digestive"],
        prepTime: "2 mins"
      },
      {
        id: "smoothies",
        name: "Smoothies",
        price: 5,
        category: "Fresh Drinks",
        description: "Creamy blended fruit smoothies: Wild Mixed Berry Acai, Mango Passionfruit Glow, or Green Spinach Banana Cleanse.",
        image: "https://images.unsplash.com/photo-1553530666-ba11a7da3888?auto=format&fit=crop&w=800&q=80",
        calories: "210 kcal",
        allergens: ["Oat Milk Option"],
        tags: ["Vegan Option", "Superfood"],
        prepTime: "4 mins"
      },
      {
        id: "fizzy-drinks",
        name: "Fizzy Drinks",
        price: 5,
        category: "Fresh Drinks",
        description: "House-crafted sparkling mocktails infused with elderflower cordial, fresh strawberries, and botanical tonic.",
        image: "https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?auto=format&fit=crop&w=800&q=80",
        calories: "110 kcal",
        allergens: [],
        tags: ["House Mocktail"],
        prepTime: "3 mins"
      },
      {
        id: "english-tea",
        name: "English Tea",
        price: 5,
        category: "Fresh Drinks",
        description: "Single-estate Assam and Ceylon Royal English Breakfast black tea served in a warm porcelain pot with whole milk and brown sugar.",
        image: "https://images.unsplash.com/photo-1576092768241-dec231879fc3?auto=format&fit=crop&w=800&q=80",
        calories: "20 kcal",
        allergens: ["Dairy Option"],
        tags: ["Loose Leaf", "Hot Drink"],
        prepTime: "4 mins"
      },
      {
        id: "green-tea",
        name: "Green Tea",
        price: 5,
        category: "Fresh Drinks",
        description: "First-flush Japanese Uji Sencha green tea delicately steamed to release grassy floral notes and natural antioxidants.",
        image: "https://images.unsplash.com/photo-1627435601361-ec25f5b1d0e5?auto=format&fit=crop&w=800&q=80",
        calories: "0 kcal",
        allergens: [],
        tags: ["Antioxidant", "Traditional"],
        prepTime: "4 mins"
      },
      {
        id: "lemonade",
        name: "Lemonade",
        price: 5,
        category: "Fresh Drinks",
        description: "Hand-squeezed organic Meyer lemons, organic turbinado cane sugar, crushed spearmint, and sparkling mountain spring water.",
        image: "https://images.unsplash.com/photo-1523677011781-c91d1bbe2f9e?auto=format&fit=crop&w=800&q=80",
        calories: "130 kcal",
        allergens: [],
        tags: ["Summer Classic", "Fresh"],
        prepTime: "3 mins"
      }
    ]
  },
  {
    id: "coffee-dessert",
    title: "Coffee & Desserts",
    shortTitle: "Coffee & Sweets",
    roman: "VII",
    discipline: "Specialty Espresso & Artisan Confections",
    note: "Single-origin espresso bar and handcrafted Italian pastries.",
    deck: "The ultimate finale: artisan coffee extracted from ethical single-origin beans paired with decadent European cakes, crèmes, and sweet parfaits.",
    binding: "Warm Walnut Cloth · Warm Gold Foil",
    format: "158 × 232 mm · Volume VII",
    theme: "Coffee & Desserts · Velvety & Decadent",
    motif: "Espresso Steam & Cocoa Bean",
    motifKey: "coffee",
    paletteLabel: "Warm Walnut · Golden Crema · Espresso",
    color: "#382017",
    foil: "#ecc380",
    palette: {
      paper: "#1e100a",
      paperDeep: "#120906",
      paperPale: "#fbf2e5",
      ink: "#fff5ea",
      inkSoft: "#d4b69d",
      wall: "#1e100a",
      shelf: "#3a2118",
      shelfDark: "#1c0e0a",
      light: "#ffeed4",
      fill: "#8c563e"
    },
    width: 1.12,
    height: 1.63,
    depth: 0.3,
    seed: 707,
    items: [
      // House Coffee
      {
        id: "flat-white",
        name: "Flat White",
        price: 5,
        category: "House Coffee",
        description: "Double ristretto extraction topped with steamed whole milk microfoam for a smooth, velvety coffee-forward cup.",
        image: "https://images.unsplash.com/photo-1577968897966-3d4325b36b61?auto=format&fit=crop&w=800&q=80",
        calories: "120 kcal",
        allergens: ["Dairy", "Oat Option"],
        tags: ["Specialty Roast", "Barista Favorite"],
        prepTime: "3 mins"
      },
      {
        id: "cafe-latte",
        name: "Cafe Latte",
        price: 5,
        category: "House Coffee",
        description: "Rich espresso blend combined with velvety steamed milk and finished with delicate hand-poured latte art.",
        image: "https://images.unsplash.com/photo-1534778101976-62847782c213?auto=format&fit=crop&w=800&q=80",
        calories: "150 kcal",
        allergens: ["Dairy"],
        tags: ["Popular"],
        prepTime: "3 mins"
      },
      {
        id: "cappuccino",
        name: "Cappuccino",
        price: 5,
        category: "House Coffee",
        description: "Equal balance of dark espresso, rich steamed milk, and a thick airy foam cap dusted with fine Valrhona cocoa powder.",
        image: "https://images.unsplash.com/photo-1517256064527-09c73fc73e38?auto=format&fit=crop&w=800&q=80",
        calories: "110 kcal",
        allergens: ["Dairy"],
        tags: ["Italian Classic"],
        prepTime: "3 mins"
      },
      {
        id: "mocha",
        name: "Mocha",
        price: 5,
        category: "House Coffee",
        description: "Double espresso infused with 70% dark Belgian chocolate syrup, steamed milk, and a swirl of whipped vanilla cream.",
        image: "https://images.unsplash.com/photo-1607681034540-2c46cc71896d?auto=format&fit=crop&w=800&q=80",
        calories: "260 kcal",
        allergens: ["Dairy"],
        tags: ["Sweet Comfort"],
        prepTime: "4 mins"
      },
      {
        id: "americano",
        name: "Americano",
        price: 5,
        category: "House Coffee",
        description: "Two shots of intense single-origin espresso drawn over hot filtered spring water for a clean, nuanced flavor profile.",
        image: "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=800&q=80",
        calories: "5 kcal",
        allergens: [],
        tags: ["Zero Calorie", "Bold"],
        prepTime: "2 mins"
      },
      {
        id: "macchiato",
        name: "Macchiato",
        price: 5,
        category: "House Coffee",
        description: "Concentrated espresso shot 'marked' with a single dollop of silky hot milk foam in a demitasse cup.",
        image: "https://images.unsplash.com/photo-1557006021-b85faa2bc5e2?auto=format&fit=crop&w=800&q=80",
        calories: "35 kcal",
        allergens: ["Dairy"],
        tags: ["Traditional"],
        prepTime: "2 mins"
      },
      {
        id: "black-coffee",
        name: "Black Coffee",
        price: 5,
        category: "House Coffee",
        description: "Slow manual pour-over of high-altitude Ethiopian Yirgacheffe beans highlighting jasmine and stone fruit aromatics.",
        image: "https://images.unsplash.com/photo-1497636577773-f1231844b336?auto=format&fit=crop&w=800&q=80",
        calories: "2 kcal",
        allergens: [],
        tags: ["Single Origin", "Pour Over"],
        prepTime: "4 mins"
      },
      {
        id: "espresso",
        name: "Espresso",
        price: 5,
        category: "House Coffee",
        description: "Pure, concentrated 30ml double shot featuring a thick hazelnut-colored tiger-stripe crema and velvety finish.",
        image: "https://images.unsplash.com/photo-1510591509098-f4fdc6d0ff04?auto=format&fit=crop&w=800&q=80",
        calories: "5 kcal",
        allergens: [],
        tags: ["Pure Extraction"],
        prepTime: "2 mins"
      },

      // Dessert Menu
      {
        id: "classic-tiramisu",
        name: "Classic Tiramisu",
        price: 10,
        category: "Dessert Menu",
        description: "Savoiardi ladyfinger biscuits dipped in fresh espresso & Marsala wine, layered with mascarpone sabayon cream and cocoa.",
        image: "https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?auto=format&fit=crop&w=800&q=80",
        calories: "460 kcal",
        allergens: ["Dairy", "Eggs", "Gluten"],
        tags: ["Signature Sweet", "Bestseller"],
        prepTime: "4 mins"
      },
      {
        id: "chocolate-cake",
        name: "Chocolate Cake",
        price: 10,
        category: "Dessert Menu",
        description: "Triple-layer moist dark chocolate fudge sponge filled with Belgian ganache and accompanied by vanilla bean gelato.",
        image: "https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&w=800&q=80",
        calories: "580 kcal",
        allergens: ["Dairy", "Eggs", "Gluten"],
        tags: ["Decadent", "Popular"],
        prepTime: "4 mins"
      },
      {
        id: "creme-brulee",
        name: "Crème Brûlée",
        price: 10,
        category: "Dessert Menu",
        description: "Silky Madagascar vanilla bean custard topped with a hand-torched, shatteringly crisp caramelized sugar crust.",
        image: "https://images.unsplash.com/photo-1470124182917-cc6e71b22ecc?auto=format&fit=crop&w=800&q=80",
        calories: "410 kcal",
        allergens: ["Dairy", "Eggs"],
        tags: ["French Classic", "Gluten-Free"],
        prepTime: "4 mins"
      },
      {
        id: "baked-alaska",
        name: "Baked Alaska",
        price: 10,
        category: "Dessert Menu",
        description: "Sponge cake foundation topped with strawberry & pistachio gelato, wrapped in toasted Swiss meringue, flamed tableside.",
        image: "https://images.unsplash.com/photo-1563729784474-d77dbb933a9e?auto=format&fit=crop&w=800&q=80",
        calories: "520 kcal",
        allergens: ["Dairy", "Eggs", "Gluten", "Nuts"],
        tags: ["Showstopper", "Chef's Choice"],
        prepTime: "6 mins"
      },
      {
        id: "green-tea-parfait",
        name: "Green Tea Parfait",
        price: 10,
        category: "Dessert Menu",
        description: "Layered Japanese dessert glass with Uji matcha sponge, sweet azuki red bean paste, matcha gelato, warabi mochi, and puffed rice.",
        image: "https://images.unsplash.com/photo-1563805042-7684c019e1cb?auto=format&fit=crop&w=800&q=80",
        calories: "390 kcal",
        allergens: ["Dairy", "Gluten"],
        tags: ["Matcha Specialty"],
        prepTime: "5 mins"
      },
      {
        id: "panna-cotta",
        name: "Panna Cotta",
        price: 10,
        category: "Dessert Menu",
        description: "Delicate vanilla bean set cream accompanied by a tart wild blackberry coulis, fresh berries, and candied mint.",
        image: "https://images.unsplash.com/photo-1488477181946-6428a0291777?auto=format&fit=crop&w=800&q=80",
        calories: "340 kcal",
        allergens: ["Dairy"],
        tags: ["Gluten-Free", "Light Finish"],
        prepTime: "4 mins"
      }
    ]
  }
];

export const ALL_MENU_ITEMS = MENU_VOLUMES.flatMap(volume => volume.items);
